package model.test;

import model.base.test.BaseKbase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kbase extends BaseKbase<Kbase> {
	public static final Kbase dao = new Kbase().dao();
}
