package model.ssk;

import model.base.ssk.BaseRegCompanyDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegCompanyDept extends BaseRegCompanyDept<RegCompanyDept> {
	public static final RegCompanyDept dao = new RegCompanyDept().dao();
}
