package model.ssk;

import model.base.ssk.BaseRegCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegCompany extends BaseRegCompany<RegCompany> {
	public static final RegCompany dao = new RegCompany().dao();
}
