package model.ssk;

import model.base.ssk.BaseRegUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegUser extends BaseRegUser<RegUser> {
	public static final RegUser dao = new RegUser().dao();
}
