package model.ssk;

import model.base.ssk.BaseRegUserDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegUserDept extends BaseRegUserDept<RegUserDept> {
	public static final RegUserDept dao = new RegUserDept().dao();
}
