package model.ssk;

import model.base.ssk.BaseXcApply;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcApply extends BaseXcApply<XcApply> {
	public static final XcApply dao = new XcApply().dao();
	public static void saveApply(String userid,String deptName,String trueName,String resources,String typeName,int type,String reason){
		new XcApply().setUserId(userid).setDeptName(deptName).setTrueName(trueName)
				.setResources(resources).setReason(reason).setCrateTime(new Date())
				.setGmtCreate(new Date().getTime()).setType(type).setTypeName(typeName).save();

	}
}
