package model.ssk;

import model.base.ssk.BaseXcAssociation;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcAssociation extends BaseXcAssociation<XcAssociation> {
	public static final XcAssociation dao = new XcAssociation().dao();
	//更加状态查询关联表信息等级
	public static List<XcAssociation> getXc(int type){
		return XcAssociation.dao.find("select * from xc_association where type=?",type);
	}

	/*//更加状态查询关联表信息等级
	public static XcAssociation getXcBytype1(int type,int userid){
		return XcAssociation.dao.findFirst("select a.id cid,a.name,a.ename,ifnull(b.type,0) type " +
				"from xc_association a left join (select type,cid from xc_apply " +
				"where userid=? and status=3 and isDeleted=false) b on a.id=b.cid where a.type=?",userid,type);

	}*/
	//更加状态查询关联表信息等级
	public static List<XcAssociation> getXcBytypes(int type,int userid,int association){
		return XcAssociation.dao.find("select a.id cid,a.name,a.ename,ifnull(b.type,0) type,a.sql,status " +
				"from xc_association a left join (select type,cid from xc_apply " +
				"where userid=? and status=3 and isDeleted=false) b on a.id=b.cid where a.type=? and a.association=?",userid,type,association);

	}
}
