package model.ssk;

import model.base.ssk.BaseXcBug;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcBug extends BaseXcBug<XcBug> {
	public static final XcBug dao = new XcBug().dao();
	public static void saveBug(String bug){
		new XcBug().setBug(bug).save();
	}
}
