package model.ssk;

import model.base.ssk.BaseXcCount;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcCount extends BaseXcCount<XcCount> {
	public static final XcCount dao = new XcCount().dao();
	public static List<XcCount> seleteXcCOunts(){
		return dao.find("select type,num from xc_count");
	}
}
