package model.ssk;

import model.base.ssk.BaseXcDatasource;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcDatasource extends BaseXcDatasource<XcDatasource> {
	public static final XcDatasource dao = new XcDatasource().dao();

	public static List<XcDatasource> getDs(int type) {
		//return dao.find("select name,typenum from xc_datasource where type=?",type);
		return dao.find("select name,sum(typenum) typenum from xc_datasource where type=? group by name",type);
	}
}
