package model.ssk;

import model.base.ssk.BaseXcInterface;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcInterface extends BaseXcInterface<XcInterface> {
	public static final XcInterface dao = new XcInterface().dao();


	public static List<XcInterface> selectXI() {
		return dao.find("select * from xc_interface order by type");
	}
}
