package model.ssk;

import model.base.ssk.BaseXcLog;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcLog extends BaseXcLog<XcLog> {
	public static final XcLog dao = new XcLog().dao();
	public static void saveLog(String userId,String log,String trueName){
		new XcLog().setUserId(userId).setGmtCreate(new Date().getTime()).setCrateTime(new Date())
	    .setLog(log).setTrueName(trueName).save();
	}
}
