package model.ssk;

import model.base.ssk.BaseXcUser;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcUser extends BaseXcUser<XcUser> {
	public static final XcUser dao = new XcUser().dao();


	public static List<XcUser> getList() {
		return dao.use("ssk").find("select * from xc_user");
	}public static XcUser getUser(String appName) {
		return dao.findFirst("select * from xc_user where appName=?",appName);
	}
	public static void saveUser(String appName,String userName,String dept,String deptCode ){
		new XcUser().setAppName(appName).setUserName(userName)
				.setDept(dept).setDeptCode(deptCode).save();
	}

}
