package model.base.ssk;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXcBug<M extends BaseXcBug<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBug(java.lang.String bug) {
		set("bug", bug);
		return (M)this;
	}
	
	public java.lang.String getBug() {
		return getStr("bug");
	}

	public M setModifyTime(java.util.Date ModifyTime) {
		set("ModifyTime", ModifyTime);
		return (M)this;
	}
	
	public java.util.Date getModifyTime() {
		return get("ModifyTime");
	}

}
