package model.base.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKuser<M extends BaseKuser<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setCShowId(java.lang.String cShowId) {
		set("C_SHOW_ID", cShowId);
		return (M)this;
	}
	
	public java.lang.String getCShowId() {
		return getStr("C_SHOW_ID");
	}

	public M setLoginName(java.lang.String loginName) {
		set("loginName", loginName);
		return (M)this;
	}
	
	public java.lang.String getLoginName() {
		return getStr("loginName");
	}

	public M setUTrueName(java.lang.String uTrueName) {
		set("U_TRUE_NAME", uTrueName);
		return (M)this;
	}
	
	public java.lang.String getUTrueName() {
		return getStr("U_TRUE_NAME");
	}

	public M setUMail(java.lang.String uMail) {
		set("U_MAIL", uMail);
		return (M)this;
	}
	
	public java.lang.String getUMail() {
		return getStr("U_MAIL");
	}

	public M setUMobile(java.lang.String uMobile) {
		set("U_MOBILE", uMobile);
		return (M)this;
	}
	
	public java.lang.String getUMobile() {
		return getStr("U_MOBILE");
	}

	public M setDName(java.lang.String dName) {
		set("D_NAME", dName);
		return (M)this;
	}
	
	public java.lang.String getDName() {
		return getStr("D_NAME");
	}

	public M setUDeptId(java.lang.String uDeptId) {
		set("U_DEPT_ID", uDeptId);
		return (M)this;
	}
	
	public java.lang.String getUDeptId() {
		return getStr("U_DEPT_ID");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}
	
	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

}
