package model.ssk;

import model.base.ssk.BaseXcMsgcount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcMsgcount extends BaseXcMsgcount<XcMsgcount> {
	public static final XcMsgcount dao = new XcMsgcount().dao();
}
