package model.base.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKlog<M extends BaseKlog<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setOUser(java.lang.String oUser) {
		set("O_USER", oUser);
		return (M)this;
	}
	
	public java.lang.String getOUser() {
		return getStr("O_USER");
	}

	public M setOUserName(java.lang.String oUserName) {
		set("O_USER_NAME", oUserName);
		return (M)this;
	}
	
	public java.lang.String getOUserName() {
		return getStr("O_USER_NAME");
	}

	public M setOpTime(java.lang.Long opTime) {
		set("OP_TIME", opTime);
		return (M)this;
	}
	
	public java.lang.Long getOpTime() {
		return getLong("OP_TIME");
	}

	public M setLOG(java.lang.String LOG) {
		set("LOG", LOG);
		return (M)this;
	}
	
	public java.lang.String getLOG() {
		return getStr("LOG");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}
	
	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

	public M setMODIFYTIME(java.util.Date MODIFYTIME) {
		set("MODIFYTIME", MODIFYTIME);
		return (M)this;
	}
	
	public java.util.Date getMODIFYTIME() {
		return get("MODIFYTIME");
	}

}
