package model.test;

import model.base.test.BaseKlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Klog extends BaseKlog<Klog> {
	public static final Klog dao = new Klog().dao();
}
