package model.ssk;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_reg_company", "ID", RegCompany.class);
		arp.addMapping("t_reg_company_dept", "ID", RegCompanyDept.class);
		arp.addMapping("t_reg_user", "ID", RegUser.class);
		arp.addMapping("t_reg_user_dept", "ID", RegUserDept.class);
		arp.addMapping("xc_apply", "id", XcApply.class);
		arp.addMapping("xc_bug", "id", XcBug.class);
		arp.addMapping("xc_count", "id", XcCount.class);
		arp.addMapping("xc_datasource", "id", XcDatasource.class);
		arp.addMapping("xc_index", "id", XcIndex.class);
		arp.addMapping("xc_interface", "id", XcInterface.class);
		arp.addMapping("xc_log", "id", XcLog.class);
		arp.addMapping("xc_msgcount", "id", XcMsgcount.class);
		arp.addMapping("xc_sourcecount", "id", XcSourcecount.class);
		arp.addMapping("xc_user", "id", XcUser.class);
	}
}

