package model.base.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKpstatus<M extends BaseKpstatus<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setOUser(java.lang.String oUser) {
		set("O_USER", oUser);
		return (M)this;
	}
	
	public java.lang.String getOUser() {
		return getStr("O_USER");
	}

	public M setOUserName(java.lang.String oUserName) {
		set("O_USER_NAME", oUserName);
		return (M)this;
	}
	
	public java.lang.String getOUserName() {
		return getStr("O_USER_NAME");
	}

	public M setOStatus(java.lang.Integer oStatus) {
		set("O_STATUS", oStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOStatus() {
		return getInt("O_STATUS");
	}

	public M setUserType(java.lang.Integer userType) {
		set("USER_TYPE", userType);
		return (M)this;
	}
	
	public java.lang.Integer getUserType() {
		return getInt("USER_TYPE");
	}

	public M setIsLook(java.lang.Integer isLook) {
		set("IS_LOOK", isLook);
		return (M)this;
	}
	
	public java.lang.Integer getIsLook() {
		return getInt("IS_LOOK");
	}

	public M setONLINE(java.lang.Integer ONLINE) {
		set("ONLINE", ONLINE);
		return (M)this;
	}
	
	public java.lang.Integer getONLINE() {
		return getInt("ONLINE");
	}

	public M setGmtCreate(java.lang.Long gmtCreate) {
		set("GMT_CREATE", gmtCreate);
		return (M)this;
	}
	
	public java.lang.Long getGmtCreate() {
		return getLong("GMT_CREATE");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("GMT_MODIFIED", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("GMT_MODIFIED");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("IS_DELETE", isDelete);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("IS_DELETE");
	}

	public M setLOOK(java.lang.Integer LOOK) {
		set("LOOK", LOOK);
		return (M)this;
	}
	
	public java.lang.Integer getLOOK() {
		return getInt("LOOK");
	}

}
