package model.test;

import model.base.test.BaseKattr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kattr extends BaseKattr<Kattr> {
	public static final Kattr dao = new Kattr().dao();
}
