package model.base.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKbase<M extends BaseKbase<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setOTitle(java.lang.String oTitle) {
		set("O_TITLE", oTitle);
		return (M)this;
	}
	
	public java.lang.String getOTitle() {
		return getStr("O_TITLE");
	}

	public M setODescribe(java.lang.String oDescribe) {
		set("O_DESCRIBE", oDescribe);
		return (M)this;
	}
	
	public java.lang.String getODescribe() {
		return getStr("O_DESCRIBE");
	}

	public M setOCreateTime(java.lang.Long oCreateTime) {
		set("O_CREATE_TIME", oCreateTime);
		return (M)this;
	}
	
	public java.lang.Long getOCreateTime() {
		return getLong("O_CREATE_TIME");
	}

	public M setLastupdateTime(java.util.Date lastupdateTime) {
		set("LASTUPDATE_TIME", lastupdateTime);
		return (M)this;
	}
	
	public java.util.Date getLastupdateTime() {
		return get("LASTUPDATE_TIME");
	}

	public M setTHUMBSNUM(java.lang.Integer THUMBSNUM) {
		set("THUMBSNUM", THUMBSNUM);
		return (M)this;
	}
	
	public java.lang.Integer getTHUMBSNUM() {
		return getInt("THUMBSNUM");
	}

	public M setLOOKNUM(java.lang.Integer LOOKNUM) {
		set("LOOKNUM", LOOKNUM);
		return (M)this;
	}
	
	public java.lang.Integer getLOOKNUM() {
		return getInt("LOOKNUM");
	}

	public M setFBNUM(java.lang.Integer FBNUM) {
		set("FBNUM", FBNUM);
		return (M)this;
	}
	
	public java.lang.Integer getFBNUM() {
		return getInt("FBNUM");
	}

	public M setOStatus(java.lang.Integer oStatus) {
		set("O_STATUS", oStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOStatus() {
		return getInt("O_STATUS");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}
	
	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

	public M setINTEGRAL(java.lang.Integer INTEGRAL) {
		set("INTEGRAL", INTEGRAL);
		return (M)this;
	}
	
	public java.lang.Integer getINTEGRAL() {
		return getInt("INTEGRAL");
	}

	public M setAttrName(java.lang.String attrName) {
		set("ATTR_NAME", attrName);
		return (M)this;
	}
	
	public java.lang.String getAttrName() {
		return getStr("ATTR_NAME");
	}

	public M setAttrPath(java.lang.String attrPath) {
		set("ATTR_PATH", attrPath);
		return (M)this;
	}
	
	public java.lang.String getAttrPath() {
		return getStr("ATTR_PATH");
	}

	public M setSendTime(java.lang.Long sendTime) {
		set("SEND_TIME", sendTime);
		return (M)this;
	}
	
	public java.lang.Long getSendTime() {
		return getLong("SEND_TIME");
	}

}
