package model.test;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("kattr", "ID", Kattr.class);
		arp.addMapping("kbase", "ID", Kbase.class);
		arp.addMapping("kfeedback", "ID", Kfeedback.class);
		arp.addMapping("klog", "ID", Klog.class);
		arp.addMapping("korder", "id", Korder.class);
		arp.addMapping("kpstatus", "ID", Kpstatus.class);
		arp.addMapping("kuser", "ID", Kuser.class);
	}
}

