package model.test;

import model.base.test.BaseKfeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kfeedback extends BaseKfeedback<Kfeedback> {
	public static final Kfeedback dao = new Kfeedback().dao();
}
