package model.test;

import model.base.test.BaseKpstatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kpstatus extends BaseKpstatus<Kpstatus> {
	public static final Kpstatus dao = new Kpstatus().dao();
}
