package model.base.ssk;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXcSourcecount<M extends BaseXcSourcecount<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setMian(java.lang.String mian) {
		set("mian", mian);
		return (M)this;
	}
	
	public java.lang.String getMian() {
		return getStr("mian");
	}

	public M setSid(java.lang.String sid) {
		set("sid", sid);
		return (M)this;
	}
	
	public java.lang.String getSid() {
		return getStr("sid");
	}

	public M setNum(java.lang.Long num) {
		set("num", num);
		return (M)this;
	}
	
	public java.lang.Long getNum() {
		return getLong("num");
	}

	public M setGmtCreate(java.lang.Long gmtCreate) {
		set("gmtCreate", gmtCreate);
		return (M)this;
	}
	
	public java.lang.Long getGmtCreate() {
		return getLong("gmtCreate");
	}

	public M setGmtModified(java.lang.Long gmtModified) {
		set("gmtModified", gmtModified);
		return (M)this;
	}
	
	public java.lang.Long getGmtModified() {
		return getLong("gmtModified");
	}

	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDeleted() {
		return get("isDeleted");
	}

	public M setCrateTime(java.util.Date crateTime) {
		set("crateTime", crateTime);
		return (M)this;
	}
	
	public java.util.Date getCrateTime() {
		return get("crateTime");
	}

	public M setModifyTime(java.util.Date modifyTime) {
		set("modifyTime", modifyTime);
		return (M)this;
	}
	
	public java.util.Date getModifyTime() {
		return get("modifyTime");
	}

}
