package model.base.ssk;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRegCompany<M extends BaseRegCompany<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setCCode(java.lang.String cCode) {
		set("C_CODE", cCode);
		return (M)this;
	}
	
	public java.lang.String getCCode() {
		return getStr("C_CODE");
	}

	public M setCName(java.lang.String cName) {
		set("C_NAME", cName);
		return (M)this;
	}
	
	public java.lang.String getCName() {
		return getStr("C_NAME");
	}

	public M setEndTime(java.util.Date endTime) {
		set("END_TIME", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("END_TIME");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("CREATE_USER", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("CREATE_USER");
	}

	public M setCreateUserName(java.lang.String createUserName) {
		set("CREATE_USER_NAME", createUserName);
		return (M)this;
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("CREATE_USER_NAME");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public M setCActivationStatus(java.lang.Integer cActivationStatus) {
		set("C_ACTIVATION_STATUS", cActivationStatus);
		return (M)this;
	}
	
	public java.lang.Integer getCActivationStatus() {
		return getInt("C_ACTIVATION_STATUS");
	}

	public M setCActivationTime(java.util.Date cActivationTime) {
		set("C_ACTIVATION_TIME", cActivationTime);
		return (M)this;
	}
	
	public java.util.Date getCActivationTime() {
		return get("C_ACTIVATION_TIME");
	}

}
