package model.base.ssk;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXcApply<M extends BaseXcApply<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setDeptName(java.lang.String deptName) {
		set("deptName", deptName);
		return (M)this;
	}
	
	public java.lang.String getDeptName() {
		return getStr("deptName");
	}

	public M setTrueName(java.lang.String trueName) {
		set("trueName", trueName);
		return (M)this;
	}
	
	public java.lang.String getTrueName() {
		return getStr("trueName");
	}

	public M setCid(java.lang.String cid) {
		set("cid", cid);
		return (M)this;
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}

	public M setResources(java.lang.String resources) {
		set("resources", resources);
		return (M)this;
	}
	
	public java.lang.String getResources() {
		return getStr("resources");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setTypeName(java.lang.String typeName) {
		set("typeName", typeName);
		return (M)this;
	}
	
	public java.lang.String getTypeName() {
		return getStr("typeName");
	}

	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}
	
	public java.lang.String getReason() {
		return getStr("reason");
	}

	public M setGmtCreate(java.lang.Long gmtCreate) {
		set("gmtCreate", gmtCreate);
		return (M)this;
	}
	
	public java.lang.Long getGmtCreate() {
		return getLong("gmtCreate");
	}

	public M setGmtModified(java.lang.Long gmtModified) {
		set("gmtModified", gmtModified);
		return (M)this;
	}
	
	public java.lang.Long getGmtModified() {
		return getLong("gmtModified");
	}

	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDeleted() {
		return get("isDeleted");
	}

	public M setCrateTime(java.util.Date crateTime) {
		set("crateTime", crateTime);
		return (M)this;
	}
	
	public java.util.Date getCrateTime() {
		return get("crateTime");
	}

	public M setModifyTime(java.util.Date modifyTime) {
		set("modifyTime", modifyTime);
		return (M)this;
	}
	
	public java.util.Date getModifyTime() {
		return get("modifyTime");
	}

}
