package model.base.ssk;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXcUser<M extends BaseXcUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAppName(java.lang.String appName) {
		set("appName", appName);
		return (M)this;
	}
	
	public java.lang.String getAppName() {
		return getStr("appName");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setDept(java.lang.String dept) {
		set("dept", dept);
		return (M)this;
	}
	
	public java.lang.String getDept() {
		return getStr("dept");
	}

	public M setDeptCode(java.lang.String deptCode) {
		set("deptCode", deptCode);
		return (M)this;
	}
	
	public java.lang.String getDeptCode() {
		return getStr("deptCode");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setShowid(java.lang.String showid) {
		set("showid", showid);
		return (M)this;
	}
	
	public java.lang.String getShowid() {
		return getStr("showid");
	}

	public M setCrateTime(java.util.Date crateTime) {
		set("crateTime", crateTime);
		return (M)this;
	}
	
	public java.util.Date getCrateTime() {
		return get("crateTime");
	}

	public M setModifyTime(java.util.Date modifyTime) {
		set("modifyTime", modifyTime);
		return (M)this;
	}
	
	public java.util.Date getModifyTime() {
		return get("modifyTime");
	}

}
