package model.base.ssk;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRegUser<M extends BaseRegUser<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setULoginName(java.lang.String uLoginName) {
		set("U_LOGIN_NAME", uLoginName);
		return (M)this;
	}
	
	public java.lang.String getULoginName() {
		return getStr("U_LOGIN_NAME");
	}

	public M setUMail(java.lang.String uMail) {
		set("U_MAIL", uMail);
		return (M)this;
	}
	
	public java.lang.String getUMail() {
		return getStr("U_MAIL");
	}

	public M setUTrueName(java.lang.String uTrueName) {
		set("U_TRUE_NAME", uTrueName);
		return (M)this;
	}
	
	public java.lang.String getUTrueName() {
		return getStr("U_TRUE_NAME");
	}

	public M setLaunchrId(java.lang.Long launchrId) {
		set("LAUNCHR_ID", launchrId);
		return (M)this;
	}
	
	public java.lang.Long getLaunchrId() {
		return getLong("LAUNCHR_ID");
	}

	public M setUName(java.lang.String uName) {
		set("U_NAME", uName);
		return (M)this;
	}
	
	public java.lang.String getUName() {
		return getStr("U_NAME");
	}

	public M setCShowId(java.lang.String cShowId) {
		set("C_SHOW_ID", cShowId);
		return (M)this;
	}
	
	public java.lang.String getCShowId() {
		return getStr("C_SHOW_ID");
	}

	public M setLastLoginToken(java.lang.String lastLoginToken) {
		set("LAST_LOGIN_TOKEN", lastLoginToken);
		return (M)this;
	}
	
	public java.lang.String getLastLoginToken() {
		return getStr("LAST_LOGIN_TOKEN");
	}

	public M setUPasswoed(java.lang.String uPasswoed) {
		set("U_PASSWOED", uPasswoed);
		return (M)this;
	}
	
	public java.lang.String getUPasswoed() {
		return getStr("U_PASSWOED");
	}

	public M setUTrueNameC(java.lang.String uTrueNameC) {
		set("U_TRUE_NAME_C", uTrueNameC);
		return (M)this;
	}
	
	public java.lang.String getUTrueNameC() {
		return getStr("U_TRUE_NAME_C");
	}

	public M setUHira(java.lang.String uHira) {
		set("U_HIRA", uHira);
		return (M)this;
	}
	
	public java.lang.String getUHira() {
		return getStr("U_HIRA");
	}

	public M setUJob(java.lang.String uJob) {
		set("U_JOB", uJob);
		return (M)this;
	}
	
	public java.lang.String getUJob() {
		return getStr("U_JOB");
	}

	public M setUNumber(java.lang.String uNumber) {
		set("U_NUMBER", uNumber);
		return (M)this;
	}
	
	public java.lang.String getUNumber() {
		return getStr("U_NUMBER");
	}

	public M setUStatus(java.lang.Integer uStatus) {
		set("U_STATUS", uStatus);
		return (M)this;
	}
	
	public java.lang.Integer getUStatus() {
		return getInt("U_STATUS");
	}

	public M setUTelephone(java.lang.String uTelephone) {
		set("U_TELEPHONE", uTelephone);
		return (M)this;
	}
	
	public java.lang.String getUTelephone() {
		return getStr("U_TELEPHONE");
	}

	public M setUMobile(java.lang.String uMobile) {
		set("U_MOBILE", uMobile);
		return (M)this;
	}
	
	public java.lang.String getUMobile() {
		return getStr("U_MOBILE");
	}

	public M setUSort(java.lang.Integer uSort) {
		set("U_SORT", uSort);
		return (M)this;
	}
	
	public java.lang.Integer getUSort() {
		return getInt("U_SORT");
	}

	public M setULanguage(java.lang.String uLanguage) {
		set("U_LANGUAGE", uLanguage);
		return (M)this;
	}
	
	public java.lang.String getULanguage() {
		return getStr("U_LANGUAGE");
	}

	public M setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("LAST_UPDATE_TIME", lastUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getLastUpdateTime() {
		return get("LAST_UPDATE_TIME");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("LAST_LOGIN_TIME", lastLoginTime);
		return (M)this;
	}
	
	public java.util.Date getLastLoginTime() {
		return get("LAST_LOGIN_TIME");
	}

	public M setIsAdmin(java.lang.Integer isAdmin) {
		set("IS_ADMIN", isAdmin);
		return (M)this;
	}
	
	public java.lang.Integer getIsAdmin() {
		return getInt("IS_ADMIN");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("CREATE_USER", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("CREATE_USER");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public M setCreateUserName(java.lang.String createUserName) {
		set("CREATE_USER_NAME", createUserName);
		return (M)this;
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("CREATE_USER_NAME");
	}

	public M setUTrueNameAc(java.lang.String uTrueNameAc) {
		set("U_TRUE_NAME_AC", uTrueNameAc);
		return (M)this;
	}
	
	public java.lang.String getUTrueNameAc() {
		return getStr("U_TRUE_NAME_AC");
	}

	public M setUIsIn(java.lang.Integer uIsIn) {
		set("U_IS_IN", uIsIn);
		return (M)this;
	}
	
	public java.lang.Integer getUIsIn() {
		return getInt("U_IS_IN");
	}

	public M setUAddress(java.lang.String uAddress) {
		set("U_ADDRESS", uAddress);
		return (M)this;
	}
	
	public java.lang.String getUAddress() {
		return getStr("U_ADDRESS");
	}

	public M setUState(java.lang.Integer uState) {
		set("U_STATE", uState);
		return (M)this;
	}
	
	public java.lang.Integer getUState() {
		return getInt("U_STATE");
	}

	public M setUIsShow(java.lang.Integer uIsShow) {
		set("U_IS_SHOW", uIsShow);
		return (M)this;
	}
	
	public java.lang.Integer getUIsShow() {
		return getInt("U_IS_SHOW");
	}

	public M setUSign(java.lang.Integer uSign) {
		set("U_SIGN", uSign);
		return (M)this;
	}
	
	public java.lang.Integer getUSign() {
		return getInt("U_SIGN");
	}

}
