package model.base.ssk;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRegCompanyDept<M extends BaseRegCompanyDept<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setDName(java.lang.String dName) {
		set("D_NAME", dName);
		return (M)this;
	}
	
	public java.lang.String getDName() {
		return getStr("D_NAME");
	}

	public M setDParentidShowId(java.lang.String dParentidShowId) {
		set("D_PARENTID_SHOW_ID", dParentidShowId);
		return (M)this;
	}
	
	public java.lang.String getDParentidShowId() {
		return getStr("D_PARENTID_SHOW_ID");
	}

	public M setDLevel(java.lang.Integer dLevel) {
		set("D_LEVEL", dLevel);
		return (M)this;
	}
	
	public java.lang.Integer getDLevel() {
		return getInt("D_LEVEL");
	}

	public M setDPath(java.lang.String dPath) {
		set("D_PATH", dPath);
		return (M)this;
	}
	
	public java.lang.String getDPath() {
		return getStr("D_PATH");
	}

	public M setDPathName(java.lang.String dPathName) {
		set("D_PATH_NAME", dPathName);
		return (M)this;
	}
	
	public java.lang.String getDPathName() {
		return getStr("D_PATH_NAME");
	}

	public M setDSort(java.lang.Integer dSort) {
		set("D_SORT", dSort);
		return (M)this;
	}
	
	public java.lang.Integer getDSort() {
		return getInt("D_SORT");
	}

	public M setCShowId(java.lang.String cShowId) {
		set("C_SHOW_ID", cShowId);
		return (M)this;
	}
	
	public java.lang.String getCShowId() {
		return getStr("C_SHOW_ID");
	}

	public M setDAvailableCount(java.lang.Integer dAvailableCount) {
		set("D_AVAILABLE_COUNT", dAvailableCount);
		return (M)this;
	}
	
	public java.lang.Integer getDAvailableCount() {
		return getInt("D_AVAILABLE_COUNT");
	}

	public M setDUnavailableCount(java.lang.Integer dUnavailableCount) {
		set("D_UNAVAILABLE_COUNT", dUnavailableCount);
		return (M)this;
	}
	
	public java.lang.Integer getDUnavailableCount() {
		return getInt("D_UNAVAILABLE_COUNT");
	}

	public M setDChilddeptCount(java.lang.Integer dChilddeptCount) {
		set("D_CHILDDEPT_COUNT", dChilddeptCount);
		return (M)this;
	}
	
	public java.lang.Integer getDChilddeptCount() {
		return getInt("D_CHILDDEPT_COUNT");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("CREATE_USER", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("CREATE_USER");
	}

	public M setCreateUserName(java.lang.String createUserName) {
		set("CREATE_USER_NAME", createUserName);
		return (M)this;
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("CREATE_USER_NAME");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public M setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("LAST_UPDATE_TIME", lastUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getLastUpdateTime() {
		return get("LAST_UPDATE_TIME");
	}

	public M setDIcon(java.lang.String dIcon) {
		set("D_ICON", dIcon);
		return (M)this;
	}
	
	public java.lang.String getDIcon() {
		return getStr("D_ICON");
	}

	public M setBACKGROUND(java.lang.String BACKGROUND) {
		set("BACKGROUND", BACKGROUND);
		return (M)this;
	}
	
	public java.lang.String getBACKGROUND() {
		return getStr("BACKGROUND");
	}

	public M setAppId(java.lang.String appId) {
		set("APP_ID", appId);
		return (M)this;
	}
	
	public java.lang.String getAppId() {
		return getStr("APP_ID");
	}

	public M setAppName(java.lang.String appName) {
		set("APP_NAME", appName);
		return (M)this;
	}
	
	public java.lang.String getAppName() {
		return getStr("APP_NAME");
	}

	public M setUSign(java.lang.Integer uSign) {
		set("U_SIGN", uSign);
		return (M)this;
	}
	
	public java.lang.Integer getUSign() {
		return getInt("U_SIGN");
	}

}
