package model.test;

import model.base.test.BaseKorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Korder extends BaseKorder<Korder> {
	public static final Korder dao = new Korder().dao();
}
