package model.test;

import model.base.test.BaseKuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kuser extends BaseKuser<Kuser> {
	public static final Kuser dao = new Kuser().dao();


	public static Kuser getKuser(String ShowId) {
		return dao.use("test").findFirst("select * from kuser where SHOW_ID=?",ShowId);

	}
}
