package model.base.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKattr<M extends BaseKattr<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setShowId(java.lang.String showId) {
		set("SHOW_ID", showId);
		return (M)this;
	}
	
	public java.lang.String getShowId() {
		return getStr("SHOW_ID");
	}

	public M setUploadUser(java.lang.String uploadUser) {
		set("UPLOAD_USER", uploadUser);
		return (M)this;
	}
	
	public java.lang.String getUploadUser() {
		return getStr("UPLOAD_USER");
	}

	public M setUploadUserName(java.lang.String uploadUserName) {
		set("UPLOAD_USER_NAME", uploadUserName);
		return (M)this;
	}
	
	public java.lang.String getUploadUserName() {
		return getStr("UPLOAD_USER_NAME");
	}

	public M setUploadTime(java.lang.Long uploadTime) {
		set("UPLOAD_TIME", uploadTime);
		return (M)this;
	}
	
	public java.lang.Long getUploadTime() {
		return getLong("UPLOAD_TIME");
	}

	public M setAttrName(java.lang.String attrName) {
		set("ATTR_NAME", attrName);
		return (M)this;
	}
	
	public java.lang.String getAttrName() {
		return getStr("ATTR_NAME");
	}

	public M setAttrPath(java.lang.String attrPath) {
		set("ATTR_PATH", attrPath);
		return (M)this;
	}
	
	public java.lang.String getAttrPath() {
		return getStr("ATTR_PATH");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}
	
	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

}
