package model.ssk;

import model.base.ssk.BaseXcSourcecount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcSourcecount extends BaseXcSourcecount<XcSourcecount> {
	public static final XcSourcecount dao = new XcSourcecount().dao();
}
